---
abstract: A publish/subscribe component for the POE framework
author:
- Nicholas Perez <nperez@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: gpl
name: POE-Component-PubSub
requires:
  Moose: '0.79'
  MooseX::Declare: '0.22'
  MooseX::Types: '0.10'
  MooseX::Types::Set::Object: '0.02'
  MooseX::Types::Structured: '0.14'
  POE: '1.005'
  POE::API::Peek: '2.15'
  POEx::Role::SessionInstantiation: '0.01'
  perl: 5.10.0
  signatures: '0.05'
resources:
  repository: git://github.com/nperez/pcps.git
version: '0.091370'
